
# PERSONALIZATION
# Site variables
name: HackCU Events
og: assets/img/og.png
logo: /assets/img/hackcu6_logo.png
original_repo: https://github.com/hackcu/events
description: Find all of HackCU's events in one place.
ga: UA-109088240-1
domain: events.hackcu.org


# Style variables
accent_color: "#22b573"
events_overlay_color: "#2697FF"
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/people.jpg

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: HackCU
author-description: "HackCU is a student organization at the University of Colorado at Boulder who brings together
    people for our annual technology and design events, HackCU and Local Hack Day. We are the largest hackathon in the Rocky Mountain Region, and
    our mission is to foster learning, designing, and building in order to turn student's ideas into a reality!"
email: contact@hackcu.org

# Social media + community variables
twitter: hackcu
fb: hackcu
fb-community: hackcu
slack-signup: https://join.slack.com/t/hackcu/shared_invite/enQtOTM2MDQ2OTY4MDUwLTNlOWQzMmRjMDM4N2UyY2EyZTI0Y2I3ZWFjMTEyNTQ3YzYzOGQyNDUwYjMyMTg2OTI5NzgzNWFhNzY4NmVhYzU

instagram: hackcu
github-org: hackcu
email-url: https://api.hackcu.org/sendgrid/events/



# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0700
  TZOFFSETTO:-0600
  TZNAME:MDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0600
  TZOFFSETTO:-0700
  TZNAME:MST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
